Repository hwsc-org/hwsc-user-svc, pull requests merged in 2019-03, with the labels that each got.

#72 Remove hard coded values when passing values to db
  go.mod
  go.sum
  service/db.go
  service/service.go
Labels: enhancement

#73 Update dockerfile
  .dockerignore
  Dockerfile
  azure-pipelines.yml
Labels: enhancement

#75 Fail test as required
  azure-pipelines-pr-test.yml
  azure-pipelines.yml
Labels: enhancement

#80 Update services to be compatible with new protocol buffers
  consts/tags.go
  go.mod
  go.sum
  service/service.go
  service/service_test.go
Labels: enhancement

#81 [WIP] Renaming tables, columns, and variables
  go.mod
  go.sum
  service/consts_test.go
  service/db.go
  service/db_test.go
  service/service.go
  service/test_fixtures/psql/0_initial_schemas.up.sql
Labels: enhancement

#82 Implement generateEmailVerifyLink
  consts/errors.go
  consts/tags.go
  service/consts_test.go
  service/db.go
  service/db_test.go
  service/email.go
  service/email_test.go
  service/service.go
  service/service_test.go
  service/utility.go
  service/utility_test.go
  tmpl/verify_email_update.html
  tmpl/verify_new_user_email.html
Labels: enhancement

#84 Implement VerifyEmailToken
  consts/errors.go
  consts/tags.go
  go.mod
  go.sum
  service/consts_test.go
  service/db.go
  service/db_test.go
  service/service.go
  service/service_test.go
  service/test_fixtures/psql/0_initial_schemas.up.sql
  service/utility.go
  service/utility_test.go
Labels: enhancement

#89 Update CreateUser
  service/service.go
Labels: enhancement

#90 Update AuthenticateUser
  consts/errors.go
  service/db.go
  service/db_test.go
  service/service.go
  service/service_test.go
Labels: enhancement

#92 Update dependencies
  go.mod
  go.sum
  service/consts_test.go
  service/db.go
  service/db_test.go
  service/service.go
  service/service_test.go
  service/utility.go
  service/utility_test.go
Labels: enhancement

#94 Reorder build and test in pipeline
  azure-pipelines-pr-test.yml
  azure-pipelines.yml
Labels: enhancement

#96 Fix dot in yaml
  azure-pipelines-pr-test.yml
  ext-azure-pipelines-pr-test.yml
Labels: bug

#98 Check to even ext and master
  README.md
Labels: enhancement

#99 try even ext and master
  README.md
Labels: enhancement

#104 Rename ext yaml file
  azure-pipelines-ext.yml
  ext-azure-pipelines-pr-test.yml
Labels: enhancement

#105 Fix docker tag
  azure-pipelines-ext.yml
  azure-pipelines-pr-test.yml
  azure-pipelines.yml
Labels: enhancement

#106 Fix wrong module path in pipeline build
  azure-pipelines-ext.yml
  azure-pipelines-pr-test.yml
  azure-pipelines.yml
Labels: bug

#109 Fix how permission level is being set
  consts/errors.go
  service/db.go
  service/db_test.go
  service/service.go
  service/service_test.go
  service/utility.go
Labels: bug, enhancement

#115 Make dummy account for account creation
  azure-pipelines-ext.yml
  azure-pipelines-pr-test.yml
  azure-pipelines.yml
  conf/config.go
  go.mod
  go.sum
  service/service.go
  service/service_test.go
  service/test_fixtures/psql/3_insert_dummy_user.down.sql
  service/test_fixtures/psql/3_insert_dummy_user.up.sql
Labels: enhancement

#116 Update grpc to 1.19.1
  go.mod
  go.sum
Labels: enhancement
